AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  MyIP:
    Description: 'IP address for SSH access'
    Type: String
  UserData:
    Description: 'Base64 encoded user data'
    Type: String
    Default: |
      #!/bin/bash
      sudo apt update -y
      sudo apt install -y python3
      sudo apt install -y python3-pip
      sudo apt install -y git
      git clone https://github.com/bar-nir/cloud-computing-ex1.git
      cd CLOUD-COMPUTING-EX2/Managers
      sudo chmod 777 app.py
      sudo pip3 install -r requirements.txt
      sudo python3 app.py &
Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-042e8287309f5df03
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      UserData:
        Fn::Base64: !Ref UserData

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-042e8287309f5df03
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      UserData:
        Fn::Base64: !Ref UserData

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP
      SecurityGroupIngress:
        - CidrIp: !Ref MyIP
          IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
Outputs:
  Instance1PublicIP:
    Description: The public IP of instance 1
    Value: !GetAtt EC2Instance1.PublicIp
  Instance2PublicIP:
    Description: The public IP of instance 2
    Value: !GetAtt EC2Instance2.PublicIp
